var lookup = {
"LowBallj": "Me",
"phitaucox": "Cox",
"danmacdonnell_admin": "Dmac",
"spork37": "Juan",
"GMoney 1.0": "Garrett",
"JBarbs88": "Barbarotta",
"larryrubio": "Rubio",
"Drew106": "Drew (Chris Friend)",
"boogs612": "Adam Berger",
"davelipman18": "Lipman",
"CFrau1693": "Chris",
"GMoney 1.0": "Garrett",
"Shaveman": "Tim",
"kshafir": "Kate (work)",
"Emily Schlosser": "Schlosser",
"JBarbs88": "Barbarotta",
"charlieshin73": "Charlie",
"katieisapeach": "Katie Cariello",
"Cariello12345": "Katie Cariello",
"KevinChristman": "Kevin",
"HeatherBarbarotta": "Barbarotta",
"FredrickMorgan": "Ricky",
"bdeemer111": "Deemer",
"krycinsk": "KK",
"COBRARED": "Dad",
"TheBranca18": "Branca",
"ESPNFAN18808142": "Timon",
"Stevie B The Legend": "Steve",
"shennigans09": "Burns",
"NBurns18": "Burns",
"jittabug824": "Kara",
"Stevie B The Legend": "Steve",
"HeatherBarbarotta": "Barbarotta",
"Giovanni7297": "Sacco",
"dfrauenberger": "Doug",
"Nsacco77": "Sacco",
"theoccho": "Occho",
"Waddles33": "Greg F",
"theoccho": "Occho",
"laurenkary07": "Kary",
"njdifiore": "Nick",
"ajamespowell": "Erin",
"bwag220": "Wags",
"Luca&#39;s Daddy": "Joe",
"cschlosser": "Schlosser",
"njdifiore": "Nick",
"marrone1982": "Mike",
"bwag220": "Wags",
"Judy Matthew": "Judy",
"Pdrito82": "Pedro",
"edepadua2": "Emily",
"uwtheta": "Lipman",
"J. Lind": "Jason (Work)",
"Rance Piatt": "Rance",
"Stone of Tucket": "Stone",
"aluball17": "Coutram",
"JohnnyStax55": "Liakos",
"br0ckst4r": "Brock",
"CPMadness": "Connor",
"Petr_Klima": "Sean Dennison",
"fdale493": "Liakos friend Kevin",
"jay10480":"Jason Saghini",
"2010TM":"Tristan",
"ltiscornia":"Larry Tiscornia",
"drefernandez01":"Greg F",
"ESPNFAN10251893": "Sean McCabe",
"espn63284498": "Ramin"
};